language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  #- sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  #- export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # GraphViz fonts
  - sudo apt-get install -qq fontconfig libfreetype6-dev
  # ImageMagick
  - sudo apt-get install -qq imagemagick
  - convert --help || true
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # GSL and other GitHubs
  - my_github=${PWD##*/}  
  - cd ..
  - git clone https://github.com/Microsoft/GSL
  - git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
  - git clone https://github.com/richelbilderbeek/RibiClasses
  - git clone https://github.com/richelbilderbeek/RibiLibraries
  - cd $my_github

services:
  - xvfb

script: 
  # Build and run tests
  - qmake -qt=qt5
  - make debug --silent
  - ./ConceptMapTest
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - find . -name SaveToImage.dot
  - find . -name SaveToImage.svg
  - cat $(find . -name SaveToImage.dot)
  - cat $(find . -name SaveToImage.svg)
